alertmanager:
  config:
    global:
      slack_api_url: <your Slack webhook>
    route:
      receiver: 'slack-notifications'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'slack-notifications'
    receivers:
    - name: 'slack-notifications'
      slack_configs:
        - channel: '#westend-notify'
          send_resolved: true

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - monitor.rico.ninja

  alertmanagerSpec:
    routePrefix: /alertmanager

grafana:
  adminPassword: prom-operator

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - monitor.rico.ninja
    path: /grafana

  grafana.ini:
    server:
      domain: monitor.rico.ninja
      root_url: 'http://monitor.rico.ninja/grafana'
      serve_from_sub_path: True

prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - monitor.rico.ninja
    path: /prometheus

  prometheusSpec:
    retention: 30d
    retentionSize: "30GB"
    routePrefix: /prometheus
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 32Gi
